name: .NET Publish

on:
  workflow_call:
    inputs:
      target:
        description: 'Target runtime'
        type: string
        required: true
      runner:
        description: 'The Operating System used for building'
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: './global.json'
          cache: true
          cache-dependency-path: 'WallProjections.Test/packages.lock.json'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: .github/requirements.txt

      - name: Install OpenCV
        run: pip install opencv-python-headless

      - name: Restore dependencies
        run: dotnet restore -r ${{ inputs.target }}

      - name: Publish
        run: >
          dotnet publish WallProjections --no-restore -c Release -r ${{ inputs.target }} \
              --sc -o $HOME/build/WallProjections --verbosity normal

      - name: Zip
        run: 7z a WallProjections-${{ inputs.target }}.zip $HOME/build/WallProjections

      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.target }}
          path: WallProjections-${{ inputs.target }}.zip
          retention-days: 1
