name: .NET CD Generic

permissions:
  contents: write
  issues: read
  pull-requests: read

on:
  workflow_call:
    inputs:
      full:
        description: 'Whether to perform a full release (true) or a development release (false)'
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Delete old `latest` release
        if: ${{ ! inputs.full }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner,
                repo,
                tag: 'latest',
              });

              if (release.data) {
                await github.rest.repos.deleteRelease({
                  owner,
                  repo,
                  release_id: release.data.id,
                });
              }
            } catch (error) {
              console.error('No release to delete');
            }

      - name: Update `latest` tag
        if: ${{ ! inputs.full }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo
            const sha = process.env.GITHUB_SHA
            try {
              await github.rest.git.updateRef({
                owner,
                repo,
                ref: `tags/latest`,
                sha,
              })
            } catch (error) {
              console.log('Tag `latest` does not exist')
            }

      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Release
        if: ${{ ! inputs.full }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Development Build
          draft: false
          prerelease: true
          body: ${{ steps.changelog.outputs.changelog }}
          generate_release_notes: true
          files: |
            *.zip

      - name: Create a Release Draft
        if: ${{ inputs.full }}
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body: ${{ steps.changelog.outputs.changelog }}
          generate_release_notes: true
          files: |
            *.zip
