name: .NET CD

permissions:
  contents: write
  issues: read
  pull-requests: read

on:
  push:
    branches:
      - dev

jobs:
  publish:
    strategy:
      matrix:
        include:
          - target: win-x64
            runner: windows-latest
          - target: osx-x64
            runner: macos-12 # Not using latest because it can be run on ARM machines, which don't support LibVLCSharp
          - target: linux-x64
            runner: ubuntu-latest
          - target: linux-arm64
            runner: ubuntu-latest
    uses: ./.github/workflows/dotnet-publish.yml
    with:
      target: ${{ matrix.target }}
      runner: ${{ matrix.runner }}

  deploy:
    needs: publish
    uses: ./.github/workflows/dotnet-cd-generic.yml
    with:
      full: false
